
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Rishab Patwari  ## put your name
title: 'Computer Engineering Undergraduate'  ## your title
location: Singapore , SG


## Social Profiles
facebook: https://www.facebook.com/rishab.patwari1 ## your facebook account url
linkedin: https://linkedin.com/in/rishab-patwari-nus  ## your linkedin account url
github: http://github.com/patwaririshab 



# Update all the sections by editing the files inside _includes folder.
